### ISSUE TITLE
Rename :editors and :viewers to :record_editors and :record_viewers

### ISSUE THREAD

**Issue by jeremyf** [ndlib/curate_nd#373]
At present we have tremendous potential for confusing method names. There exists :editors and :viewers. This works up until we add metadata regarding a book's editor.

## Todo

- [ ] Rename `editors` references to `record_editors`
- [ ] Rename `editor_groups` references to `record_editor_groups`
- [ ] Rename `viewers` references to `record_viewers`
- [ ] Rename `viewer_groups` references to `viewer_record_groups`

See #372
